### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by lukasl-dev** [laurensk/digi4school-pdf#2]
![image](https://user-images.githubusercontent.com/56000765/103937323-e657fd80-5128-11eb-87ef-92b197499083.png)

Any solutions?

**Comment by laurensk** [comment]
Hey @lukasl-dev! Could it be that you have tried to download an open book? These are the books which are currently to read on digi4school. Open books are not supported to download.

Let me know if that was the problem! If it's still not working, please comment again on this issue.
