### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by ReitererLukas** [laurensk/digi4school-pdf#8]
After downloading all pages, it happened to me that the `mergePdfs()` function was called to early.

![image](https://user-images.githubusercontent.com/45203024/165072430-152f3111-1fc2-4a77-bd66-2656204f68d8.png)

The problem was that the last pdf file hasn't been saved to the system yet (most likely svg-to-pdf uses an async function to save files). I resolved the problem by setting a timeout before calling the `mergePdfs()` function. 

`setTimeout(this.mergePdfs, 3000);`
This would replace [line 281](https://github.com/laurensk/digi4school-pdf/blob/85b953dd4dbf117babe00e2f1d74ad19fcd1a48a/src/D4SDownloader.ts#L281)

Unfortunately I am not allowed to push my changes and create a pull request, otherwise I would have done that, instead of creating a new issue.

Hope it helps!
Ciao Lukas

**Comment by laurensk** [comment]
Hey @ReitererLukas, thanks for letting me know! I will try to fix the problem since just adding a timeout isn't a great solution imo.

Thanks again!
