### ISSUE TITLE
Not generating all Pages

### ISSUE THREAD

**Issue by PreiMat** [laurensk/digi4school-pdf#9]
Somehow the script dosen't generate all Pages.
It should be 284 Pages -
![image](https://user-images.githubusercontent.com/107151157/201359715-261d8f03-7561-4343-8dbd-da07498a181a.png)

but the script breaks before finishing with no Traceback. The only information is `Source is not an Array`
![image](https://user-images.githubusercontent.com/107151157/201359880-91f061e5-e3f1-4bfa-a6e4-783d07ecda6b.png)

I tried to find the error by myself but i wasn't able to find it.

**Comment by laurensk** [comment]
Hi @PreiMat, thanks for reaching out. This repository is no longer maintained, so I do not plan to fix any new issues. There is a new version of this program available, but I decided to not open source it - reach out to me via email if you want to learn more!

All the best, Laurens

**Comment by PreiMat** [comment]
Hello Laurens,

ich bin ziemlich interessiert in diesem Program.

MfG,
Matthias

Zitat von Laurens Kropf ***@***.***>:

**Comment by laurensk** [comment]
Alright. Schreib mir am besten auf Discord. Laurens#4045

**Comment by StefanM135** [comment]
> Hi @PreiMat, thanks for reaching out. This repository is no longer maintained, so I do not plan to fix any new issues. There is a new version of this program available, but I decided to not open source it - reach out to me via email if you want to learn more!
> 
> All the best, Laurens

Wie kann ich dich per Mail kontaktieren? Wäre ebenfalls daran interessiert.
Mfg. Stefan

**Comment by laurensk** [comment]
Hi Stefan, schreib mir am besten auf Discord @ scarybugz
